# Generated by Django 4.0.1 on 2022-03-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('key_skills', models.CharField(max_length=255)),
                ('exp', models.CharField(max_length=255)),
                ('required_language', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('created_datetime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'career',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CareerApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('hq_per', models.CharField(max_length=255)),
                ('high_school', models.CharField(max_length=255)),
                ('higher_sec', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('resume', models.FileField(default='', upload_to='career/resume')),
                ('created_datetime', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'career_applicant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=255)),
                ('hq_per', models.CharField(max_length=255)),
                ('high_school', models.CharField(max_length=255)),
                ('higher_sec', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('resume', models.CharField(max_length=255)),
                ('created_datetime', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'career_application',
                'managed': False,
            },
        ),
    ]
